### ISSUE TITLE
初始化窗口时崩溃

### ISSUE THREAD

**Issue by wangxun2008** [AngryAccelerated/Physics2D-TestBed-SFML#2]
![image](https://github.com/user-attachments/assets/804c9a27-9e8c-454e-8ed5-812f3f36d319)
![image](https://github.com/user-attachments/assets/2d73aa80-4261-40f4-a672-e841d04ba8b0)
我在运行时出现了一点错误，似乎是在初始化窗口时的问题，生成是成功的，但是运行后会崩溃，提示了一行信息，我没用过SMFL和ImGUI，不知道怎么解决？

**Comment by acrlw** [comment]
我这里是正常的，你用的 SFML 是哪个版本的？我的版本是 2.6.1，我查到这个错误是 SFML 内的错误，你可以试一下自己用 SFML 库创建一个窗口是否成功。

**Comment by wangxun2008** [comment]
我看了一下，我是2.6.0的版本

**Comment by wangxun2008** [comment]
测试了一下，创建窗口没有问题欸

**Comment by acrlw** [comment]
> 测试了一下，创建窗口没有问题欸

这个部分的代码就是普通的创建窗口，照理来说，你把你的创建窗口的代码替换掉这个，一样可以运行

**Comment by wangxun2008** [comment]
![image](https://github.com/user-attachments/assets/8523404a-09b5-48dc-bc06-be52a29cce34)
我用SFML创建了窗口，这样似乎可以运行的。但使用ImGui::SFML::Init()好像就会崩溃，似乎是ImGui的问题，我明天再看看

**Comment by acrlw** [comment]
> ![image](https://private-user-images.githubusercontent.com/88886127/353898946-8523404a-09b5-48dc-bc06-be52a29cce34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDIxNjAsIm5iZiI6MTcyMjQ0MTg2MCwicGF0aCI6Ii84ODg4NjEyNy8zNTM4OTg5NDYtODUyMzQwNGEtMDliNS00OGRjLWJjMDYtYmU1MmEyOWNjZTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2MDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2E0NjQ5NjU1MmM1NWE2YjQwZjJmZmQ5OWEzODhkNmIwZmZhMTZjMWU4NTkwMTEzMjA5OWNhNTY2ODZiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4FBDx2ckSfbF7JaO4p3Rfd2dVp7qieRb8eT_akJ9p0U) 我用SFML创建了窗口，这样似乎可以运行的。但使用ImGui::SFML::Init()好像就会崩溃，似乎是ImGui的问题，我明天再看看

你的 ImGui-SFML 是什么版本的？我的是 2.6 ，我之前在 2.5 的时候运行不了。

**Comment by wangxun2008** [comment]
嗯，xmake帮我安装了ImGui-SFML 2.5，应该是这个问题了
